---
title: "barplots"
author: "Filippos Kardaras"
date: "2/14/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Create bacteria composition Heatmap, grouped by hospital environment
```{r libraries_and_import}
library(qiime2R)
library(tibble)
library(tidyverse)
library(xlsx)
library(this.path())
library(ape)
# library("phyloseq")

project_dir=this.path::here(..=1)
tables_directory=paste0(project_dir,"/data/intermediate/06_frequency_filtering")
plots_dir=paste0(project_dir, "/results/plots")
supp2_plots_dir=file.path(project_dir,"results/supplementary_plots_2")
#heatmap_dir=file.path(project_dir,"data/intermediate/10_heatmap")
dir.create(supp2_plots_dir, showWarnings = FALSE)
#dir.create(heatmap_dir, showWarnings = FALSE)
metadata_file=paste0(project_dir,"/data/16S_3batches_metadata.tsv")
metadata<-read_q2metadata(metadata_file)


```
# Heatmaps Genus level
```{r plot genus_heatmaps}
####GENUS
#CREATE "_Other" taxon 
OTUs<-read_qza(file.path(tables_directory,"filtered_table_l6.qza"))$data
OTUs<-apply(OTUs, 2, function(x) x/sum(x)*100) #convert to percent
OTUs_simplified= OTUs %>%
  as.data.frame() %>%
  rownames_to_column("Feature.ID") %>%
  mutate(Feature.ID=if_else(grepl("g__$",Feature.ID,fixed=FALSE), "_Other", Feature.ID)) %>%  #those classified at genus "g__" will be marked as _Other
  mutate(Feature.ID=if_else(grepl("g__",Feature.ID,fixed=FALSE), Feature.ID, "_Other")) #those not classified at a genus will also be marked as _Other (they do not contain g__)

#select top 4 from each sample
OTUsToPlot<-  
  OTUs_simplified %>%
  gather(-Feature.ID, key="SampleID", value="Abundance") %>%
  group_by(SampleID) %>%
  mutate(Abundance=if_else(Feature.ID == "__Other",  NA_real_, Abundance )) %>% #flag features to be collapsed
  mutate(Abundance=if_else(Abundance == 0,  NA_real_, Abundance )) %>% #flag features to be collapsed
  group_by(SampleID, Feature.ID) %>%
  summarize(Abundance=sum(Abundance)) %>%
  group_by(SampleID) %>%  
  slice_max(Abundance,n=4) %>%
  pull(Feature.ID) %>% #extract only the names from the table
  unique 
OTUs_composition_table=
  OTUs_simplified %>%
  as.data.frame() %>%
  gather(-Feature.ID, key="SampleID", value="Abundance") %>%
  mutate(Feature.ID=if_else((Feature.ID %in% OTUsToPlot) | (Feature.ID =="_Other"),  Feature.ID, "_Low abundant")) %>% #flag features to be collapsed
  group_by(SampleID, Feature.ID) %>%
  summarize(Abundance=sum(Abundance)) %>%
  left_join(metadata[,1:16]) %>%
  mutate(NormAbundance=log10(Abundance+0.01)) %>% # do a log10 transformation after adding a 0.01% pseudocount. Could also add 1 read before transformation to percent
  mutate(Taxon=gsub("k__.*g__", "", Feature.ID)) %>%
  mutate(Taxon=gsub(";s__.*", "", Taxon)) 
#plot1
OTUs_composition_table%>%
  ggplot(aes(x=SampleID, y=Taxon, fill=NormAbundance)) +
  geom_tile() +
  facet_grid(~`type2`, scales="free_x", space="free_x") +
  theme_q2r() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  #theme(strip.text = element_text(angle=90, hjust=0, size =8))+
  scale_fill_viridis_c(name="log10(% Abundance)")
ggsave(file.path(supp2_plots_dir,"Genus_heatmap.pdf"), height=5, width=11, device="pdf") # save a PDF
ggsave(file.path(supp2_plots_dir,"Genus_heatmap.png"), height=5, width=11, device="png") # save a png
```


# barplot
```{r barplot genera}
barplot = taxa_barplot(OTUs, metadata, "type2", ntoplot = 10)
barplot[["data"]][["Taxon"]]=gsub("k__.*g__", "", barplot[["data"]][["Taxon"]])
barplot[["data"]][["Taxon"]]=gsub(";s__.*", "", barplot[["data"]][["Taxon"]])
barplot[["data"]][["Taxon"]]=gsub("Remainder", " Remainder", barplot[["data"]][["Taxon"]])
# barplot[["data"]][["Taxon"]]=ifelse(barplot[["data"]][["Taxon"]]=="Enterococcus","Enterococcus","_")
barplot + ylab("Relative Abundance (%)") +
  theme(strip.text.x = element_text(size = 11, angle = 0), axis.title.y=element_text(size = 11))
ggsave(file.path(plots_dir,"Figure_4.png"), height=5, width=11, device="png")
ggsave(file.path(plots_dir,"Figure_4.pdf"), height=5, width=11, device="pdf")

```

```{r heatmap family level}
####FAMILY
#CREATE "_Other" taxon for unassigned at this level
OTUs<-read_qza(file.path(tables_directory,"filtered_table_l5.qza"))$data
OTUs<-apply(OTUs, 2, function(x) x/sum(x)*100) #convert to percent
OTUs_simplified= OTUs %>%
  as.data.frame() %>%
  rownames_to_column("Feature.ID") %>%
  mutate(Feature.ID=if_else(grepl("f__$",Feature.ID,fixed=FALSE), "_Other", Feature.ID)) %>%  
  mutate(Feature.ID=if_else(grepl("f__",Feature.ID,fixed=FALSE), Feature.ID, "_Other")) 
# select top 4 from each sample
OTUsToPlot<-  
  OTUs_simplified %>%
  gather(-Feature.ID, key="SampleID", value="Abundance") %>%
  group_by(SampleID) %>%
  mutate(Abundance=if_else(Feature.ID == "__Other",  NA_real_, Abundance )) %>% #flag features to be collapsed
  mutate(Abundance=if_else(Abundance == 0,  NA_real_, Abundance )) %>% #flag features to be collapsed
  group_by(SampleID, Feature.ID) %>%
  summarize(Abundance=sum(Abundance)) %>%
  group_by(SampleID) %>%  
  slice_max(Abundance,n=4) %>%
  pull(Feature.ID) %>% #extract only the names from the table
  unique 
OTUs_composition_table=
  OTUs_simplified %>%
  as.data.frame() %>%
  gather(-Feature.ID, key="SampleID", value="Abundance") %>%
  mutate(Feature.ID=if_else((Feature.ID %in% OTUsToPlot) | (Feature.ID =="_Other"),  Feature.ID, "_Low abundant")) %>% #flag features to be collapsed
  group_by(SampleID, Feature.ID) %>%
  summarize(Abundance=sum(Abundance)) %>%
  left_join(metadata[,1:16]) %>%
  mutate(NormAbundance=log10(Abundance+0.01)) %>% # do a log10 transformation after adding a 0.01% pseudocount. Could also add 1 read before transformation to percent
  mutate(Taxon=gsub("k__.*f__", "", Feature.ID)) %>%
  mutate(Taxon=gsub(";g__.*", "", Taxon)) 
#plot 1
OTUs_composition_table %>%
  ggplot(aes(x=SampleID, y=Taxon, fill=NormAbundance)) +
  geom_tile() +
  facet_grid(~`type2`, scales="free_x", space="free_x") +
  theme_q2r() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  #theme(strip.text = element_text(angle=90, hjust=0, size =8))+
  scale_fill_viridis_c(name="log10(% Abundance)")
ggsave(file.path(supp2_plots_dir,"Family_heatmap.pdf"), height=5, width=11, device="pdf") # save a PDF 3 inches by 4 inches
ggsave(file.path(supp2_plots_dir,"Family_heatmap.pdf"), height=5, width=11, device="png") # save a PDF 3 inches by 4 inches

#barplot
barplot = taxa_barplot(OTUs, metadata, "type2", ntoplot = 10)
barplot[["data"]][["Taxon"]]=gsub("k__.*f__", "", barplot[["data"]][["Taxon"]])
barplot[["data"]][["Taxon"]]=gsub(";g__.*", "", barplot[["data"]][["Taxon"]])
barplot[["data"]][["Taxon"]]=gsub("Remainder", " Remainder", barplot[["data"]][["Taxon"]])
barplot
ggsave(file.path(supp2_plots_dir,"top_10_Families_barplot.png"), height=5, width=11, device="png")
ggsave(file.path(supp2_plots_dir,"top_10_Families_barplot.pdf"), height=5, width=11, device="pdf")


```

```{r}
####Phylum
#CREATE "_Other" taxon for unassigned at this level
OTUs<-read_qza(file.path(tables_directory,"filtered_table_l2.qza"))$data
OTUs<-apply(OTUs, 2, function(x) x/sum(x)*100) #convert to percent
OTUs_simplified= OTUs %>%
  as.data.frame() %>%
  rownames_to_column("Feature.ID") %>%
  mutate(Feature.ID=if_else(grepl("p__$",Feature.ID,fixed=FALSE), "_Other", Feature.ID)) %>%  
  mutate(Feature.ID=if_else(grepl("p__",Feature.ID,fixed=FALSE), Feature.ID, "_Other")) 
# select top 4 from each sample
OTUsToPlot<-  
  OTUs_simplified %>%
  gather(-Feature.ID, key="SampleID", value="Abundance") %>%
  group_by(SampleID) %>%
  mutate(Abundance=if_else(Feature.ID == "__Other",  NA_real_, Abundance )) %>% #flag features to be collapsed
  mutate(Abundance=if_else(Abundance == 0,  NA_real_, Abundance )) %>% #flag features to be collapsed
  group_by(SampleID, Feature.ID) %>%
  summarize(Abundance=sum(Abundance)) %>%
  group_by(SampleID) %>%  
  slice_max(Abundance,n=4) %>%
  pull(Feature.ID) %>% #extract only the names from the table
  unique 
OTUs_composition_table=
  OTUs_simplified %>%
  as.data.frame() %>%
  gather(-Feature.ID, key="SampleID", value="Abundance") %>%
  mutate(Feature.ID=if_else((Feature.ID %in% OTUsToPlot) | (Feature.ID =="_Other"),  Feature.ID, "_Low abundant")) %>% #flag features to be collapsed
  group_by(SampleID, Feature.ID) %>%
  summarize(Abundance=sum(Abundance)) %>%
  left_join(metadata[,1:16]) %>%
  mutate(NormAbundance=log10(Abundance+0.01)) %>% # do a log10 transformation after adding a 0.01% pseudocount. Could also add 1 read before transformation to percent
  mutate(Taxon=gsub("k__.*p__", "", Feature.ID)) %>%
  mutate(Taxon=gsub(";c__.*", "", Taxon)) 
#plot
OTUs_composition_table %>%
  ggplot(aes(x=SampleID, y=Taxon, fill=NormAbundance)) +
  geom_tile() +
  facet_grid(~`type2`, scales="free_x", space="free_x") +
  theme_q2r() +
  theme(axis.text.x=element_text(angle=45, hjust=1)) +
  theme(strip.text = element_text(angle=90, hjust=0, size =8))+
  scale_fill_viridis_c(name="log10(% Abundance)")
ggsave(file.path(supp2_plots_dir,"Phylum_heatmap.pdf"), height=5, width=11, device="pdf") # save a PDF 3 inches by 4 inches
ggsave(file.path(supp2_plots_dir,"Phylum_heatmap.png"), height=5, width=11, device="png") # save a PDF 3 inches by 4 inches
```
```{r excel phyla}
#save excel
# compare_groups=
#   OTUs_composition_table %>%
#   group_by(Taxon, type) %>%
#   summarize(Abundance=mean(Abundance)) %>%
#   spread(key="type", value = "Abundance") %>%
#   mutate_if(is.numeric, round, digits = 2)
# write.xlsx(as.data.frame(compare_groups), file.path(out_dir,"hospital_heatmaps","Phylum_mean_abundance.xlsx"), row.names=FALSE)

```
```{r barplot_phyla}
barplot = taxa_barplot(OTUs, metadata, "type2", ntoplot = 10)
barplot[["data"]][["Taxon"]]=gsub("k__.*p__", "", barplot[["data"]][["Taxon"]])
barplot[["data"]][["Taxon"]]=gsub(";c__.*", "", barplot[["data"]][["Taxon"]])
barplot[["data"]][["Taxon"]]=gsub("Remainder", " Remainder", barplot[["data"]][["Taxon"]])
#barplot +  theme(strip.text = element_text(angle=90, hjust=0, size =8))
barplot
ggsave(file.path(supp2_plots_dir,"top_10_Phyla_barplot.png"), height=5, width=11, device="png")
ggsave(file.path(supp2_plots_dir,"top_10_Phyla_barplot.pdf"), height=5, width=11, device="pdf")

```
# hierarchical clustering heatmap
```{r hierarchical_clustering_a}
# load GENUS level table
OTUs_Genus<-read_qza(file.path(project_dir,"data/intermediate/06_frequency_filtering/filtered_table_l6.qza"))$data
OTUs_fixed = OTUs_Genus
rownames(OTUs_fixed) = gsub("k__.*g__", "", rownames(OTUs_fixed))
rownames(OTUs_fixed) = gsub(";s__.*", "", rownames(OTUs_fixed) )
rownames(OTUs_fixed)[rownames(OTUs_fixed)==""] = "Other"
OTUs_fixed = rowsum(OTUs_fixed, row.names(OTUs_fixed), )
OTUs_fixed <- t(OTUs_fixed)
OTUdf = as.data.frame(OTUs_fixed)
#transform the raw counts of reads to proportions
OTUdf.prop <- OTUdf/rowSums(OTUdf)*100

#print heatmap
scaleyellowred <- colorRampPalette(c("lightyellow", "red"), space = "rgb")(100)
heatmap(as.matrix(OTUdf.prop), Rowv = NA, Colv = NA, col = scaleyellowred, cexRow= 0.5, cexCol = 0.2)
```
```{r hc_continue}
# determine the maximum relative abundance for each column
maxab <- apply(OTUdf.prop, 2, max)
head(maxab)
# remove the taxa with less than 5% as their maximum relative abundance
n5 <- names(which(maxab < 5))
n5=c(n5,"Other")
OTUdf.prop.5 <- OTUdf.prop[, -which(names(OTUdf.prop) %in% n5)]


#color patient groups
group=(metadata[,c("SampleID","type")] %>% filter(!(SampleID %in% c("SE-15",
                                                                    "NE-27",
                                                                    "SE-04",
                                                                    "SE-08"))))$type
group = as.character(group)
colors = replace(group, which(group== "negative"), "#56B4E9")
colors = replace(colors, which(colors== "asymptomatic"), "#999999")
colors = replace(colors, which(colors== "mild"), "orange")
colors = replace(colors, which(colors== "severe"), "brown")

#print heatmap with highly abundant taxa and with group colors
heatmap(as.matrix(OTUdf.prop.5), scale="none", RowSideColors = colors, Rowv = NA, Colv = NA, col = scaleyellowred, margins = c(10, 2))

#measure bray curtis distance of rarefied samples
bray_dist=read_qza(file.path(project_dir,"/data/intermediate/08_core_metrics/core_metrics_phylogenetic/bray_curtis_distance_matrix.qza"))$data
row.clust <- hclust(bray_dist, method="average")
heatmap(as.matrix(OTUdf.prop.5), scale="none", RowSideColors = colors, Rowv =as.dendrogram(row.clust), Colv = NA, col = scaleyellowred, margins = c(10, 2))

```
```{r hc_continue2}
#You can also add a column dendrogram to cluster the genera that occur more often together. Note that this one must be done on the same dataset that is used in the Heatmap (i.e. reduced number of genera).
# you have to transpose the dataset to get the genera as rows
taxa.dist <- vegan::vegdist(t(OTUdf.prop.5), method = "bray")
col.clus <- hclust(taxa.dist, "aver")

# make the heatmap with Rowv = as.dendrogram(row.clus)
heatmap(log10(as.matrix(OTUdf.prop.5+0.01)), scale="none", RowSideColors = colors, 
        Rowv =as.dendrogram(row.clust), 
        Colv = as.dendrogram(col.clus), col = scaleyellowred, margins = c(10, 2))



####Save the heatmap
pdf(file.path(plots_dir,"Figure_5.pdf"),height=12, width=10)
gplots::heatmap.2(log10(as.matrix(OTUdf.prop.5+0.01)),
          Rowv = as.dendrogram(row.clust), 
          Colv = as.dendrogram(col.clus), 
          col = scaleyellowred, 
          RowSideColors = colors, 
          margins = c(10, 5), 
          trace = "none", density.info = "none",
          scale="none",
          xlab = "Genus", ylab = "Samples", main = "Heatmap of Bacterial Relative Abundance", 
          lhei = c(1, 7), # this makes the colour-key legend a little thinner
          key.xlab ="Log10(Abundance%+0.01%)") 
par(lend = 1)
legend(xy.coords(0,0), lwd = 6,
       legend = c("negative", "asymptomatic", "mild", "severe"),
       col = c("#56B4E9", "#999999", "orange", "brown"),
       xpd=TRUE)
while (!is.null(dev.list()))  dev.off()


```